### ISSUE TITLE
Please stop bundling third-party libraries

### ISSUE THREAD

**Issue by tarsius** [skeeto/markov-text#1]
markov-text is mirrored on the [Emacsmirror](https://github.com/emacsmirror), which is a large up-to-date collection of Emacs packages.

As the maintainer of the mirror I am trying to resolve feature conflicts that result from one package bundling libraries from another package.  I suspect in most cases these libraries were included so that users would not have to find, download and install each dependency manually.

Unfortunately bundling also has negative side-effects: if the bundled libraries are also installed separately, then it is undefined which version actually gets loaded when the respective feature is required.

Initially that isn't a big problem but in many cases upstream changes are not included or only after a long delay.  This can be very confusing for users who are not aware that some of the installed packages bundle libraries which are also installed separately.  In other cases bugs are fixed in the bundled versions but the fixes are never submitted to upstream.

Also now that Emacs contains the package.el package manager there is a better way to not require users to manually deal with dependencies: add the package (and when that hasn't been done yet the dependencies) to the [Melpa](https://github.com/milkypostman/melpa) package repository.  If `make` is required to install your make you might want to add it to the [el-get](https://github.com/dimitri/el-get) (another popular package manager) package repository instead.

Alternatively if you want to keep bundling these libraries please move them to a directory only containing bundled libraries and add the file ".nosearch" to that directory.  You can then load the library using something like this:

```
(or (require 'bundled nil t)
    (let ((load-path
           (cons (expand-file-name "fallback-libs"
                                   (or load-file-name buffer-file-name)
                                   load-path))))
      (require 'bundled)))
```

Of course if your version differs from the upstream version this might not be enough in which case you should make an effort to get your changes merged upstream.

markov-text bundles at least the following libraries:
- lorem-ipsum

Best regards,
Jonas

**Comment by skeeto** [comment]
lorem-ipsum.el is entirely my own source so you're seeing a name collision with someone else. In fact, it extends this markov-text library, so, if anything, markev-text.el is the bundled library here. None of my Elisp repositories on GitHub bundle third-party Elisp code.

How would you like to manage name collisions? markox-text.el and lorem ipsum.el aren't meant to be used by anyone else as part of their editor. It's just me using Elisp as a general programming language.

**Comment by tarsius** [comment]
Great, the tab just crashed... that's what I get for writing outside of Emacs... retyped answer in a bit :-(

**Comment by tarsius** [comment]
Sorry for not noticing that this actually is a name conflict.  Now I consider neither lorem-ipsum nor markov-text to be the bundled library.

I have considered mirroring both version when a name conflict occurs - but that would require significant changes to my import tools and it's not worth it.  There actually aren't that many name conflicts and if there is one it is often easy to decide which implementation has to go.

In this case I will also just remove one implementation, probably the one from the Emacswiki.  lorem-ipsum is not exactly mission critical :-)  Therefor I think it is okay to just take the easy way out...

**Comment by skeeto** [comment]
Thanks for your hard work cataloging and mirroring all these Emacs packages.

**Comment by tarsius** [comment]
You're welcome. When people reply as timely as you just did, it's actually a pleasure :-)
