### ISSUE TITLE
lorem-ipsum.el conflicts with other library by same name

### ISSUE THREAD

**Issue by tarsius** [skeeto/markov-text#2]
Your `lorem-ipsum.el` conflicts with another implementation from https://github.com/jschaf/emacs-lorem-ipsum.

**Comment by skeeto** [comment]
We had this discussion [just over 3 years ago](https://github.com/skeeto/markov-text/issues/1). This repository isn't really meant to be used as a normal package by other people, so conflicts shouldn't matter. Plus my lorem-ipsum was first. :-)

**Comment by tarsius** [comment]
Sorry about that!
